source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'pg'
gem 'thin'
gem 'devise'
gem 'omniauth-google-oauth2'
gem 'nested_form'
gem 'auto_html'
gem 'will_paginate'
gem 'delayed_job_active_record'
#gem 'newrelic_rpm'
gem 'paperclip'
gem 'ckeditor'
gem 'request-log-analyzer'
gem 'exception_notification'

group :development do 
    gem 'better_errors'
    gem 'binding_of_caller'
    gem 'quiet_assets'
    gem 'mailcatcher'
    gem 'hirb'
    gem 'railroady'
    #gem 'populator'
    #gem 'faker'
    gem 'zeus'
    gem 'debugger'
end

group :assets do
	gem 'therubyracer'
	gem 'less-rails' 
	# gem 'libv8'
    gem 'sass-rails',   '~> 3.2.3'
  	gem 'coffee-rails', '~> 3.2.1'
  	gem 'uglifier', '>= 1.0.3'
    gem 'jquery-ui-rails'
    gem 'compass-rails'
    gem 'bootstrap-sass', '~> 3.1.1'
    gem 'bootstrap-slider-rails'
    #gem 'bootstrap-wysihtml5-rails'
    gem 'bootstrap-colorpicker-rails'
    gem 'jquery-datatables-rails', '~> 2.1.10.0.3'
    #gem 'jquery_datepicker'
    gem 'flot-rails'
    gem 'jquery-sparkline-rails', git: 'https://github.com/RobAtHedtek/jquery-sparkline-rails.git'
    gem 'json'
end

gem 'jquery-rails'