development:
  adapter: postgresql
  encoding: unicode
  database: mess_mail_development
  pool: 5
  username: amandeepsingh
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mess_mail_test
  pool: 5
  username: amandeepsingh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mess_mail_production
  pool: 5
  username: amandeepsingh
  password: 